language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1

services:
  - mysql

dist: trusty

sudo: required

env:
  matrix:
    - DB=mysql db_dsn='mysql://root@0.0.0.0/mamook_test'

before_install:
  - mysql -e "create database IF NOT EXISTS mamook_test;" -uroot

before_script:
  - composer install --prefer-dist --no-interaction

notifications:
  email: false