language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1

services:
  - mysql

dist: trusty

sudo: required

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

before_install:
  - sudo apt-get -y install mysql-server;
  - mysql -u root -e 'CREATE DATABASE mamook_test;';

before_script:
  - composer install --prefer-dist --no-interaction

matrix:
  allow_failures:
    - php: 7.0
    - php: 7.1

  fast_finish: true