language: php

php:
  - 5.5
  - 5.6

services:
  - mysql

dist: trusty

sudo: false

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

before_install:
  - sudo apt-get -y install mysql-server;
  - mysql -u root -e 'CREATE DATABASE mamook_test;';

before_script:
  - composer install --prefer-dist --no-interaction